use role ACCOUNTADMIN;


CREATE OR REPLACE SECURITY INTEGRATION 
  SALESFORCE_DATA_CLOUD_OAUTH_INTEGRATION
  TYPE = OAUTH
  OAUTH_CLIENT = CUSTOM
  OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
  OAUTH_REDIRECT_URI = ‘https://login.salesforce.com/services/cdpSnowflakeOAuthCallback'
  PRE_AUTHORIZED_ROLES_LIST = ('SALESFORCE_DATA_CLOUD_READER')
  ENABLED = TRUE 
  OAUTH_ISSUE_REFRESH_TOKENS = TRUE;